<?php

namespace AppBundle\Repository;

/**
 * TodolistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodolistRepository extends \Doctrine\ORM\EntityRepository
{
}
